### ISSUE TITLE
Find command Linux symbolic link issue

### ISSUE THREAD

**Issue by lashower** [yuanchuan/find#12]
Issue:
When running a file search in a directory and the directory is a symbolic link, then no results are returned.

OS: Raspbian Jessie
Hardware: Raspberry Pi 3
NodeJS Version: v8.9.1
NPM Version: 5.5.1
find version: 0.2.7

Code used:
```
var searchFiles = function(directory,expression)
{
    var promise = new Promise((resolve,reject) => {
        var results = [];
        find.file(new RegExp(expression),directory,(files) => {
            files.forEach(file => {
                results.push({path:file,name:path.basename(file)});
            })
            resolve(results);
        }).error((err) => {
            logger.error("Monitor","searchFiles",err);
            logger.debug("Monitor","searchFiles",directory,expression)
                resolve(results);
        })
    })
    return promise;
}
searchFiles('/home/pi/.emulationstation','(.*)log(.*)')
```

Simple example to reproduce:
```
mkdir /tmp/test1
cd /tmp/test1
touch mylog1.txt
touch mylog2.txt
cd /tmp
ln -s test1 test2
ln -s test1 .test3
cd <node_directory>
node
const find = require('find')
var directory='/tmp/test1'
var expression='(.*)log(.*)'
find.file(new RegExp(expression),directory,(files) => { console.log(files) });
directory='/tmp/test2'
find.file(new RegExp(expression),directory,(files) => { console.log(files) });
directory='/tmp/.test3'
find.file(new RegExp(expression),directory,(files) => { console.log(files) });
```

Possible workaround:
```
const fs = require('fs-extra');
var checkDir = function(dir) {
    var promise = new Promise((resolve,reject) => {
        fs.exists(dir).then(exist => {
            if(!exist)
            {
                resolve(null);
            } else
            {
                fs.realpath(dir).then(result => { resolve(result) });
            }
        });
    });
    return promise;
}
directory='/tmp/.test3'
checkDir(directory).then(realDir => {
    find.file(new RegExp(expression),realDir,(files) => { console.log(files) });
})
```

Keep in mind, this issue is only if the last path in the directory is a symbolic link. For example, if I created /tmp/test1/testFolder and run find on /tmp/test2/testFolder, then it would work.

**Comment by yuanchuan** [comment]
Fixed in v0.2.8!

**Comment by lashower** [comment]
I can recreate a ticket, but it doesn't seem like your fix works.

In my example above it fails in the /tmp/test2 and /tmp/.test3 runs.

Here is my test results:
```
> const find = require('find'); var directory='/tmp/test1'; var expression='(.*)log(.*)'
undefined
> var test1 = find.file(new RegExp(expression),directory,(files) => { console.log(files) });
undefined
> [ '/tmp/test1/mylog1.txt', '/tmp/test1/mylog2.txt' ]
> directory='/tmp/test2'
'/tmp/test2'
var test2 = find.file(new RegExp(expression),directory,(files) => { console.log(files) });
undefined
> Error: ENOENT: no such file or directory, lstat '/home/pi/nodejs/lab/test1'
    at Object.fs.lstatSync (fs.js:941:11)
    at Object.directory (/home/pi/nodejs/lab/node_modules/find/index.js:53:19)
    at traverseAsync (/home/pi/nodejs/lab/node_modules/find/index.js:161:10)
    at /home/pi/nodejs/lab/node_modules/find/index.js:272:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
directory='/tmp/.test3'
> var test3 = find.file(new RegExp(expression),directory,(files) => { console.log(files) });
undefined
> Error: ENOENT: no such file or directory, lstat '/home/pi/nodejs/lab/test1'
    at Object.fs.lstatSync (fs.js:941:11)
    at Object.directory (/home/pi/nodejs/lab/node_modules/find/index.js:53:19)
    at traverseAsync (/home/pi/nodejs/lab/node_modules/find/index.js:161:10)
    at /home/pi/nodejs/lab/node_modules/find/index.js:272:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Although I was able to test this successfully in non-tmp directories like /home/pi/.config/test2

**Comment by yuanchuan** [comment]
I just followed your example and It worked on my computer.

**Comment by yuanchuan** [comment]
I've created a helper script named `find.js` for quick test:

```js
#!/usr/local/bin/node

const find = require('find');
const dir = process.argv[2];

if (dir !== undefined) {
  console.log(
    find.fileSync(dir)
  )
}
```

Under the tested path there is a folder named `test` and a symbolic link `test1` pointing to it.

The result:

```bash
>./find.js ./test
[ 'test/test.js' ]

> ./find.js ./test1
[ 'test1/test.js' ]
```

**Comment by yuanchuan** [comment]
Any news?

**Comment by lashower** [comment]
My apologies. Been incredibly busy and was sick on top of it.

So I created your find.js in my project and ran this
```
mkdir /tmp/test1
cd /tmp/test1
touch mylog1.txt
touch mylog2.txt
cd /tmp
ln -s test1 test2
ln -s test1 .test3
cd ~/nodejs/lab
node test.js /tmp/test1
```

> [ '/tmp/test1/mylog1.txt', '/tmp/test1/mylog2.txt' ]

`node test.js /tmp/test2`

> /home/pi/nodejs/lab/node_modules/find/index.js:33
>       throw err;
>       ^
> 
> Error: ENOENT: no such file or directory, lstat '/home/pi/nodejs/lab/test1'
>     at Object.fs.lstatSync (fs.js:941:11)
>     at Object.directory (/home/pi/nodejs/lab/node_modules/find/index.js:53:19)
>     at traverseSync (/home/pi/nodejs/lab/node_modules/find/index.js:219:10)
>     at Object.find.(anonymous function) [as fileSync] (/home/pi/nodejs/lab/node_modules/find/index.js:364:5)
>     at Object.<anonymous> (/home/pi/nodejs/lab/test.js:6:18)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)
> 

`node test.js /tmp/.test3`

> /home/pi/nodejs/lab/node_modules/find/index.js:33
>       throw err;
>       ^
> 
> Error: ENOENT: no such file or directory, lstat '/home/pi/nodejs/lab/test1'
>     at Object.fs.lstatSync (fs.js:941:11)
>     at Object.directory (/home/pi/nodejs/lab/node_modules/find/index.js:53:19)
>     at traverseSync (/home/pi/nodejs/lab/node_modules/find/index.js:219:10)
>     at Object.find.(anonymous function) [as fileSync] (/home/pi/nodejs/lab/node_modules/find/index.js:364:5)
>     at Object.<anonymous> (/home/pi/nodejs/lab/test.js:6:18)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)
> 

`ls -lad /tmp/*test*`
> drwxr-xr-x 2 pi pi 4096 Jan 26 11:09 /tmp/test1
> lrwxrwxrwx 1 pi pi    5 Jan 26 11:09 /tmp/test2 -> test1

`ls -lad /tmp/.test*`

> lrwxrwxrwx 1 pi pi 5 Jan 26 11:09 /tmp/.test3 -> test1

**Comment by yuanchuan** [comment]
Thanks for the detailed logs.  I've located the bug now.

**Comment by yuanchuan** [comment]
This PR should fix it

**Comment by yuanchuan** [comment]
Please try v0.2.9

**Comment by lashower** [comment]
Beautiful. Working great now.

**Comment by yuanchuan** [comment]
Great! Let's close it.
