### ISSUE TITLE
Ignore Folders

### ISSUE THREAD

**Issue by mightytyphoon** [yuanchuan/find#17]
Hi,

I'm using find and I would like to ignore some folders during the search (such as node_modules), are you planning to do it ? If no, can you direct me to the file/function/line to change so I do it myself ?

Thanks a lot.

**Comment by yuanchuan** [comment]
Hi @mightytyphoon, somehow I missed the notification...

The easiest way might be filtering files afterwards, if performance is not crucial:

```js
function ignoreNodeModules(fn) {
  return name => {
    if (!/node_modules/.test(name)) {
      fn(name);
    }
  }
}

find.file(__dirname, ignoreNodeModules(name => {
  console.log(name);
});
```

Or

```js
function ignoreNodeModules(input) {
  return input.filter(n => !/node_modules/.test(n));
}

let all = ignoreNodeModules(find.fileSync(__dirname));

```
