### ISSUE TITLE
Allow alternative file systems to be used

### ISSUE THREAD

**Issue by dazinator** [yuanchuan/find#18]
Hello!

More background on this: https://github.com/dependents/node-module-lookup-amd/issues/20

I'd like to submit a PR to allow an alternative `fs` implementation to be passed in via `options`. When one is passed in, then that can be used instead of node's default `fs`. This will open up scenarios such as being able use virtual file systems with tools such as `union-fs` but without overriding node's default implementation which would effect dynamic imports and dependency resolution at runtime.

Would you be open to such a PR?

**Comment by dazinator** [comment]
Looking at the code, I am not sure what the simplest way to achieve this would be.
I'm veering towards creating a factory function, that will execute as an IIFE, with default `fs` passed in as an argument, then refactoring most of the functions to operate within that paradigm.
Then in order to use this library with an alternative `fs` you could call the factory function passing your own `fs` as a parameter..

Maybe I am missing something simple?

**Comment by dazinator** [comment]
PR Submitted #21

**Comment by dazinator** [comment]
Yep it was a bit of a struggle on my part. Thanks for considering :-)

**Comment by dazinator** [comment]
Did you manage to investigate this one any further in the end?

**Comment by yuanchuan** [comment]
Ah sorry. Maybe one more month
