### ISSUE TITLE
find.file does not find symbolic links pointing to files

### ISSUE THREAD

**Issue by fps** [yuanchuan/find#2]
Possibly due to using fs.lstat whch handles symbolic links differently from files. The best course of action would probably be to resolve symbolic links for files only and check the pointee. You probably do not want to do that for directories to avoid cycles (and which I suppose is the reason for using lstat in the first place).

**Comment by yuanchuan** [comment]
hi @fps , sorry for the delay in reply. I've been to Mars for the past year and just came to Earth. `find.file` follows symbolic links now.
