### ISSUE TITLE
symbolic links are followed relative to root path rather than the symlink itself

### ISSUE THREAD

**Issue by zelitzsi** [yuanchuan/find#5]
We are using connect-gzip-static which utilizes find and recently started experiencing ENOENT errors, I think due to [this fix](https://github.com/yuanchuan/find/issues/2). 

Consider a symlink named **fileA** with the contents **"fileB"**. I would expect that the symlink would be followed within the same directory - however, I think find is looking for the file in the current working directory + "/fileB".

**Comment by yuanchuan** [comment]
sorry about that, please try v0.2.2

**Comment by zelitzsi** [comment]
Seems to work as expected, thanks for the quick turnaround!
