### ISSUE TITLE
How to use pattern matching to find a file in a directory?

### ISSUE THREAD

**Issue by nelsonic** [yuanchuan/find#6]
Hi @yuanchuan,
We are trying to use your `find` module to search for a file called `hi.js` which we have in our project,

Using the following code:
```js
var find = require('find');

find.file(/hi\.js$/, function(file) {
  console.log(files.length);
});
```
We run this in the root directory: https://github.com/nelsonic/other/blob/master/find_file.js
And the `hi.js` file is located in: https://github.com/nelsonic/other/blob/master/test/tmp/hi.js

but we get:
```sh
Error: /hi\.js$/ does not exists.
```

What are we doing wrong...? (e.g: _is the regular expression incorrect_?)

Thanks!

**Comment by yuanchuan** [comment]
The `root` parameter is missing. Try the following:

```javascript
var find = require('find');

find.file(/hi\.js$/, './',  function(file) {
  console.log(files.length);
});
```

**Comment by nelsonic** [comment]
Sweet. Thanks! :+1:

**Comment by nelsonic** [comment]
Is there an equivalent ***synchronous*** method?

**Comment by yuanchuan** [comment]
You're welcome.  Yes you can use `find.fileSync` and `find.dirSync` to find files synchronously. (more info in readme file.)

**Comment by nelsonic** [comment]
Cool.
We would like to use this module for our app, would you accept a Pull Request extending the documentation?
Thanks!

**Comment by yuanchuan** [comment]
Of course, that would be great!

**Comment by mrjoelkemp** [comment]
Can we close this issue?

**Comment by nelsonic** [comment]
yes, thanks! 👍
