### ISSUE TITLE
API is not nodeback-compatible

### ISSUE THREAD

**Issue by joepie91** [yuanchuan/find#7]
Currently, the typical function signature in this module looks like this:

`doThing(someArgument, function(result) { ... }).error(function(err) { ... })`

... however, to conform to the nodeback (Node.js callback) convention, it should look like this:

`doThing(someArgument, function(err, result) { ... })`

... where err is an Error object.

In the current situation, the API is confusing as it's not consistent with other asynchronous libraries, and it's not possible to use third-party tools with it that expect nodebacks - for example, you can't promisify this library (which is an issue I ran into and got stuck on for a while). Similarly, it wouldn't be possible to use it with the `async` module.

Changing the API would be a breaking change, and thus require incrementing the major version number.

**Comment by yuanchuan** [comment]
Good point, I'll take a look at this.

**Comment by mems** [comment]
The workaround I use:

```javascript
const {promisify} = require("util");
const findFile = promisify((file, ...args) => {
	const [pat, root, fn] = args.length === 2 ? ['', ...args] : args;
	file(pat, root, result => fn(undefined, result)).error(fn);
}).bind(this, require("find").file);
...
const files = await findFile(/\.png$/i, "/my/path");
```

Instead of:

```javascript
const {promisify} = require("util");
// Can't be used like that:
const findFile = promisify(require("find").file);
...
const files = await findFile(/\.png$/i, "/my/path");
```

**Comment by yuanchuan** [comment]
@mems  Thanks for the tip.
