### ISSUE TITLE
Create a cli for find

### ISSUE THREAD

**Issue by erikvold** [yuanchuan/find#8]
It would be nice if I could do `npm install -g find` and then use `find` as a global cli.

**Comment by erikvold** [comment]
@yuanchuan sound good to you?

**Comment by yuanchuan** [comment]
Sounds nice!  Though only problem might be the name conflict with the gnu or BSD `find` and varying in functionality with them.

**Comment by mrjoelkemp** [comment]
What about `npm-find` as a binary name?

**Comment by yuanchuan** [comment]
`npm-find` might means finding a npm package？

**Comment by mrjoelkemp** [comment]
Yeah, it's not the best name. The convention is to differentiate the OS
find from the npm package find.

find-file or some derivative would also work.

**Comment by slmgc** [comment]
I calling the binary `node-find` might be a better choice.
